/**
 * Intel resolution helpers for runtime feed interactions.
 */

import type { GameState } from '../state/types'
import { GameError } from '../state/types'

interface IntelFeedUpsertResult {
  state: GameState
  generated: boolean
  upgraded: boolean
}

/**
 * Add or refresh the intel report generated by a given action/event key.
 * If no authored intel report matches generated_by, returns input state unchanged.
 */
export function upsertIntelFeedByGenerator(
  state: GameState,
  generatorKey: string,
  turn: number
): IntelFeedUpsertResult {
  const report = state.content?.intel_reports.intel_reports.find((item) => item.generated_by === generatorKey)
  if (!report) {
    return { state, generated: false, upgraded: false }
  }

  const feed = [...(state.intel_feed ?? [])]
  const index = feed.findIndex((item) => item.report_key === report.report_key)
  const urgent = report.urgency === 'high' || report.urgency === 'critical'
  if (index >= 0) {
    const existing = feed[index]
    if (!existing) {
      return { state, generated: false, upgraded: false }
    }
    const upgraded = existing.occurred_at !== turn
    feed[index] = {
      ...existing,
      occurred_at: turn,
      is_read: false,
      is_urgent: urgent,
    }
    return {
      state: {
        ...state,
        intel_feed: feed,
      },
      generated: false,
      upgraded,
    }
  }

  feed.push({
    report_key: report.report_key,
    occurred_at: turn,
    is_read: false,
    is_urgent: urgent,
  })
  return {
    state: {
      ...state,
      intel_feed: feed,
    },
    generated: true,
    upgraded: false,
  }
}

/**
 * Marks a report as read in state.intel_feed.
 * Throws when the report key is unknown in the runtime feed.
 */
export function markIntelReportRead(state: GameState, reportKey: string): GameState {
  const feed = state.intel_feed
  if (!feed) {
    throw new GameError('Intel feed not initialized', 'INTEL_FEED_NOT_INITIALIZED')
  }

  let found = false
  const nextFeed = feed.map((item) => {
    if (item.report_key !== reportKey) {
      return item
    }
    found = true
    if (item.is_read) {
      return item
    }
    return {
      ...item,
      is_read: true,
    }
  })

  if (!found) {
    throw new GameError(`Intel report not found in feed: ${reportKey}`, 'INTEL_REPORT_NOT_FOUND')
  }

  return {
    ...state,
    intel_feed: nextFeed,
  }
}
